### ISSUE TITLE
Updating article crashes

### ISSUE THREAD

**Issue by ksuhiyp** [ksuhiyp/blog#5]
Request PUT/http://localhost:3000/articles
body
```
title:vasxzsss
body:dasds
author:5b8d9e351dfaa317559c4c58
description:asdg
tags:5b8c65f4cc9fa4570acf32ca
tags:5b8c663e13d53f586e2e5559
tags:5b8c67ff13d53f586e2e555a
//categories:5b852f423f78e538be17aea7
categories:5b8d1a014691f96192b7007f
//categories:5b852f473f78e538be17aea8
```
`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
application.js:630
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/home/idea/DEV/blog/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/idea/DEV/blog/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/idea/DEV/blog/node_modules/express/lib/response.js:267:15)
    at doc.save.then (/home/idea/DEV/blog/controllers/article.js:120:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by ksuhiyp** [comment]
#7 duplicated
